### ISSUE TITLE
accounts.deploy : error when the gas limit is not set

### ISSUE THREAD

**Issue by qSlnz** [HyperLink-Technology/brownie#125] opened 2019-05-13 13:26 UTC
* `brownie` Version: v1.0.0b5
* `solc` Version: 0.5.7
* `Python` Version: 3.6.3
* OS: linux

### What was wrong?

I encountered a bug when deploying a contract when gas limits are not configured.

```bash
$ brownie console
```
```python
Using solc version v0.5.7
Brownie v1.0.0b5 - Python development framework for Ethereum

Using solc version v0.5.7
Brownie environment is ready.

>>> a[0].deploy(SafeMath)

  File "brownie/cli/console.py", line 112, in _run
    exec(cmd, self.__dict__, local_)
  File "<string>", line 1, in <module>
  File "brownie/network/account.py", line 215, in deploy
    txid = _raise_or_return_tx(e)
  File "brownie/network/account.py", line 332, in _raise_or_return_tx
    data = eval(str(exc))
SyntaxError: invalid syntax (<string>, line 1)

# I think the bug come from here :
# brownie/network/account.py:deploy:

try:
     txid = self._transact({
     'from': self.address,
     'value': wei(amount),
     'gasPrice': wei(gas_price) or self._gas_price(),

     # This line, and specifically the self._gas_limit function call
     'gas': wei(gas_limit) or self._gas_limit(amount, data),
     'data': HexBytes(data)
})
except ValueError as e:
      txid = _raise_or_return_tx(e)
```
I think ths arguments are out of place. The function _gas_limit is called with (amount, data) arguments, but _gas_limit function is defined by _gas_limit(self, to, amount, data=""). So, 'amount' refers to 'to', and 'data' refers to 'amount'.

I solved my problem by manually configuring gas_limit to avoid the _gas_limit function and thus bypassing the crashing branch :

a[0].deploy(SafeMath, gas_limit=500000)

It works, but ofc the main problem is still here.

**Comment by iamdefinitelyahuman** [comment] 2019-05-13 17:02
Sorry...  this is a result of me moving too quickly and breaking things.  You're right about the cause of the issue.  I have a fix implemented in a branch I'm about to push, and I'll try to get another release out before the end of the day.

Version `1.0.0b5` was all about code refactoring prior to writing unit tests. My next focus is writing those tests so that this doesn't happen anymore :)

**Comment by iamdefinitelyahuman** [comment] 2019-05-13 22:09
Fix has been merged and a new version pushed to Pypi

**Closed by iamdefinitelyahuman** 2019-05-13 22:09 UTC
